spring.datasource.url=jdbc:postgresql://localhost:5432/mod_gestao_musical
spring.datasource.username=SEU_USUARIO_POSTGRES
spring.datasource.password=SUA_SENHA_POSTGRES

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

mod.security.username=SEU_USUARIO_BASIC_AUTH
mod.security.password=SUA_SENHA_BASIC_AUTH